/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DebrupGUI;

import Debrup.ProgressTracker;
import Debrup.Student;

/**
 *
 * @author dhali
 */
public class ProgressMenuGUI extends javax.swing.JFrame {
    private Student student;
    private ProgressTracker tracker;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProgressMenuGUI.class.getName());

    /**
     * Creates new form ProgressMenuGUI
     */
     public ProgressMenuGUI(Student student, ProgressTracker tracker) {
        initComponents();
        this.student = student;
        this.tracker = tracker;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guiLBL = new javax.swing.JLabel();
        quizBTN = new javax.swing.JButton();
        progressBTN = new javax.swing.JButton();
        leaderboardBTN = new javax.swing.JButton();
        dashboardBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        guiLBL.setText("EDUTRACK - STUDENT PROGRESS TRACKING");

        quizBTN.setText("ATTEMPT QUIZ");
        quizBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quizBTNActionPerformed(evt);
            }
        });

        progressBTN.setText("MY PROGRESS");
        progressBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                progressBTNActionPerformed(evt);
            }
        });

        leaderboardBTN.setText("LEADERBOARD");

        dashboardBTN.setText("DASHBOARD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(guiLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(leaderboardBTN)
                            .addComponent(quizBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(progressBTN))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(dashboardBTN)))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(guiLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quizBTN)
                    .addComponent(progressBTN))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leaderboardBTN)
                    .addComponent(dashboardBTN))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quizBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quizBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quizBTNActionPerformed

    private void progressBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_progressBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_progressBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dashboardBTN;
    private javax.swing.JLabel guiLBL;
    private javax.swing.JButton leaderboardBTN;
    private javax.swing.JButton progressBTN;
    private javax.swing.JButton quizBTN;
    // End of variables declaration//GEN-END:variables
}
